### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by safwankdb** [Leosocy/RobustPalmRoi#20]
' ' '
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-4faf6b6d6085> in <module>
      4 import io
      5 with open('7.JPG', 'rb') as palm:
----> 6     roi_bytes = chain.process_image(palm)
      7     roi = io.BytesIO(roi_bytes)
      8     roi.show()

~/anaconda3/lib/python3.7/site-packages/robust_palm_roi-0.1.0-py3.7.egg/rpr.py in process_image(self, image)
     62         self._lib.chain_process_bytes(self._chain, palm_data, len(palm_data),
     63                                       roi_bytes, roi_bytes_max_size, roi_bytes_size, status)
---> 64         self._check_status(status)
     65         return roi_bytes.raw[:roi_bytes_size.value]
     66 

~/anaconda3/lib/python3.7/site-packages/robust_palm_roi-0.1.0-py3.7.egg/rpr.py in _check_status(status)
     68     def _check_status(status):
     69         if status.raw[0] != 0:
---> 70             raise RuntimeError(status.raw[1:].decode())

RuntimeError:
' ' '

**Comment by leosocy** [comment]
What is the error message printed by runtime error?

**Comment by zhucebuliaopx** [comment]
i met the same error,the runtime error message was just empty

**Comment by leosocy** [comment]
> i met the same error,the runtime error message was just empty

Did you specify the config yaml file path?

**Comment by zhucebuliaopx** [comment]
> > i met the same error,the runtime error message was just empty
> 
> Did you specify the config yaml file path?

i just use the py_sample/run_sample & palm_data/ ,it's normal when i using example pic.the error raises  when i use myself pic,not all pic but some of them.

**Comment by pytpeng** [comment]
just like this

Traceback (most recent call last):
  File "run_sample.py", line 24, in <module>
    roi_bytes = chain.process_image(palm)
  File "/Users/peng/workspace/RobustPalmRoi-fvzQl-Kc/lib/python3.7/site-packages/robust_palm_roi-0.1.0-py3.7.egg/rpr.py", line 64, in process_image
  File "/Users/peng/workspace/RobustPalmRoi-fvzQl-Kc/lib/python3.7/site-packages/robust_palm_roi-0.1.0-py3.7.egg/rpr.py", line 70, in _check_status
RuntimeError:

**Comment by zhucebuliaopx** [comment]
like this 

/Users/peng/boo/tmp/RobustPalmRoi/samples/palm_data/4121565314936_.pic.jpg
OrigNormalizer cost time: 10.301000 ms
LaplaceEnhancer cost time: 2.207000 ms
GaussianFilter cost time: 3.121000 ms
OtsuBinarizer cost time: 9.401000 ms
NoiseAdjuster cost time: 1.807000 ms
AngleAdjuster cost time: 17.502000 ms
PeakValleyDetector cost time: 1.556000 ms
HandlerChain total cost time: 45.895000 ms
Traceback (most recent call last):
  File "run_sample.py", line 25, in <module>
    roi_bytes = chain.process_image(palm)
  File "/Users/peng/workspace/RobustPalmRoi-fvzQl-Kc/lib/python3.7/site-packages/robust_palm_roi-0.1.0-py3.7.egg/rpr.py", line 64, in process_image
  File "/Users/peng/workspace/RobustPalmRoi-fvzQl-Kc/lib/python3.7/site-packages/robust_palm_roi-0.1.0-py3.7.egg/rpr.py", line 70, in _check_status
RuntimeError:

**Comment by leosocy** [comment]
@pytpeng Can you provide the palm picture which cause the error if convenient?

**Comment by pytpeng** [comment]
@Leosocy 
![4121565314936_ pic](https://user-images.githubusercontent.com/29520335/62815372-cf376980-bb4a-11e9-87d1-67c64b2e2343.jpg)

**Comment by zhucebuliaopx** [comment]
@Leosocy https://user-images.githubusercontent.com/29520335/62815372-cf376980-bb4a-11e9-87d1-67c64b2e2343.jpg
