### ISSUE TITLE
Python LoadLibrary error: "undefined symbol: _ZTIN4YAML13BadConversionE"

### ISSUE THREAD

**Issue by romqn1999** [Leosocy/RobustPalmRoi#23]
Hi, after successful installation library and python module, I run the python sample and got this error
`
Traceback (most recent call last):
  File "/home/dacle/anaconda3/envs/dacle/lib/python3.8/site-packages/robust_palm_roi-0.1.0-py3.8.egg/rpr.py", line 27, in __init__
  File "/home/dacle/anaconda3/envs/dacle/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/dacle/anaconda3/envs/dacle/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/librobust-palm-roi.so: undefined symbol: _ZTIN4YAML13BadConversionE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samples/py_sample/run_sample.py", line 19, in <module>
    chain = HandlerChain(ALGORITHM_CONFIG)
  File "/home/dacle/anaconda3/envs/dacle/lib/python3.8/site-packages/robust_palm_roi-0.1.0-py3.8.egg/rpr.py", line 30, in __init__
OSError: Library [librobust-palm-roi] not found.
Please see https://github.com/Leosocy/RobustPalmRoi/blob/master/README.md#Installation
`

**Comment by romqn1999** [comment]
I was able to resolve this by change [this](https://github.com/Leosocy/RobustPalmRoi/blob/a3dd8144d68c3d5af53314dce91ddbb3ac450470/CMakeLists.txt#L83) line to `TARGET_LINK_LIBRARIES(${LIBRARY_NAME} ${OpenCV_LIBS} yaml-cpp ${LINK_LIBRARIES})`
